add port and config parameters
pmu-tech/stub-server pull request #5
Opened 2020-01-28 03:38 UTC by gko

closes #4

2020-01-28 16:54 UTC, tkrotoff commented
Would have been interesting to use yargs since jest-runtime/jest-cli already depends on it. Doesn't matter much https://www.npmtrends.com/commander-vs-yargs

2020-01-28 23:24 UTC, tkrotoff requested changes

2020-01-28 23:24 UTC, tkrotoff commented on package.json
> +    "commander": "^4.1.0",
`commander` should be in the dependencies otherwise `bin/stub-server` will fail at runtime.

Would have been interesting to use yargs since jest-runtime/jest-cli already depends on it (https://github.com/pmu-tech/stub-server/blob/fc83b29b3025d0ff8840fda714fd96a1c54bf781/package-lock.json#L5102). Doesn't matter much https://www.npmtrends.com/commander-vs-yargs

2020-01-28 23:26 UTC, tkrotoff commented
I've added a new branch `test-bin/stub-server`: https://github.com/pmu-tech/stub-server/tree/test-bin/stub-server

It tests `bin/stub-server`, to be reviewed and merged after this branch has been merged.

2020-01-28 23:30 UTC, tkrotoff commented
README.md should also be updated: https://github.com/pmu-tech/stub-server/blob/fc83b29b3025d0ff8840fda714fd96a1c54bf781/README.md#command-line

2020-01-29 06:52 UTC, gko commented on package.json
> +    "commander": "^4.1.0",
Commander has twice the stars on Github and six times less issues than yargs

2020-01-29 08:18 UTC, gko commented
> I've added a new branch `test-bin/stub-server`: https://github.com/pmu-tech/stub-server/tree/test-bin/stub-server
> 
> It tests `bin/stub-server`, to be reviewed and merged after this branch has been merged.

it seems to me that we're testing `commander` there. The only functional change for me is the fact that we're casting the `port` from `string` to a `number`.

2020-01-29 08:55 UTC, gko commented
> README.md should also be updated: https://github.com/pmu-tech/stub-server/blob/fc83b29b3025d0ff8840fda714fd96a1c54bf781/README.md#command-line

#7

2020-01-29 09:02 UTC, tkrotoff commented on bin/stub-server.js
> +cmd.option('-p, --port <port>', 'stub server port').option('-c, --config <config>', 'config file');
Defaults should be documented/set here.
See https://github.com/tj/commander.js/#default-option-value

2020-01-29 14:08 UTC, tkrotoff approved these changes

2020-01-29 14:09 UTC, merged